"use-client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Wallet from "./components/Wallet";
import NavBar from "./components/NavBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-tr overflow-x-hidden min-w-screen from-zinc-950 via-stone-900 to-neutral-950 flex min-h-screen flex-col items-center justify-between">
        <main className="p-4 py-10 gap-6 w-full lg:w-[70%]">
          <Wallet>
            <NavBar />
            {children}
          </Wallet>
        </main>
      </body>
    </html>
  );
}
